development:
    database:
        driver: mysql
        user: root
        password: root
        name: hoge
        logPath: /aaa/bbb/query.log
        logMode: true
    log:
        maxAge: 1
        maxBackup: 3

staging:
    database:
        driver: mysql
        user: root
        password: root
        name: hoge
        logPath: /aaa/bbb/query.log
        logMode: true
    log:
        maxAge: 1
        maxBackup: 3

production:
    database:
        driver: mysql
        user: root
        password: root
        name: hoge
        logPath: /aaa/bbb/query.log
        logMode: false
    log:
        maxAge: 1
        maxBackup: 3
